#!/bin/sh

sed -i 's/\\<\([^>]*\)>/\\x\1 /g; s/\\isactrlbold {\\isacharless}//g; s/\\isactrlbold {\\isachargreater}//g' ./Phi_Logic_Programming_Reasoner.tex

xelatex root.tex
xelatex root.tex
xelatex root.tex
