#!/bin/sh

sed -i 's/\\<\([^>]*\)>/\\x\1 /g; s/\\isactrlbold {\\isacharless}//g; s/\\isactrlbold {\\isachargreater}//g' ./Phi_Semantics_Framework.tex ./Resource_Space.tex

xelatex root.tex
xelatex root.tex
xelatex root.tex
